/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageDatabasePanel.java
 *
 * Created on Aug 25, 2011, 12:10:37 PM
 */
package org.ut.biolab.medsavant.view.menu;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.ut.biolab.medsavant.olddb.ManageDB;
import org.ut.biolab.medsavant.olddb.MedSavantDatabase;
import org.ut.biolab.medsavant.olddb.table.ModifiableColumn;
import org.ut.biolab.medsavant.olddb.table.ModifiableTableSchema;
import org.ut.biolab.medsavant.olddb.table.TableSchema.ColumnType;
import org.ut.biolab.medsavant.db.exception.NonFatalDatabaseException;
import org.ut.biolab.medsavant.view.ViewController;

/**
 *
 * @author mfiume
 */
public class ManageDatabasePanel extends javax.swing.JPanel {

    private String tableComboDefault = "Choose table to modify";
    private ModifiableTableSchema currentSchema; 
    private ModifiableColumn currentColumn;
    
    /** Creates new form ManageDatabasePanel */
    public ManageDatabasePanel() {
        initComponents();
        
        columnList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                Object o = columnList.getSelectedValue();
                if(o != null){
                    populateDetails((ModifiableColumn)o);
                }      
            }
        });
        columnNameField.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) {}
            public void focusLost(FocusEvent e) {
                if(currentColumn != null){
                    currentColumn.setColumnName(columnNameField.getText());
                }
            }
        });
        shortNameField.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) {}
            public void focusLost(FocusEvent e) {
                if(currentColumn != null){
                    currentColumn.setShortName(shortNameField.getText());
                }
            }
        });
        descriptionField.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) {}
            public void focusLost(FocusEvent e) {
                if(currentColumn != null){
                    currentColumn.setDescription(descriptionField.getText());
                }
            }
        });
        typeCombo.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if(currentColumn != null){
                    currentColumn.setType((ColumnType)typeCombo.getSelectedItem());
                }
            }
        });
        lengthField.addFocusListener(new FocusListener() {
            public void focusGained(FocusEvent e) {}
            public void focusLost(FocusEvent e) {
                if(currentColumn == null) return;
                try {
                    currentColumn.setLength(Integer.parseInt(lengthField.getText()));
                } catch (NumberFormatException ex){
                    lengthField.setText(String.valueOf(currentColumn.getLength()));
                }             
            }
        });       
        useAsFilterCheckBox.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                if(currentColumn != null){
                    currentColumn.setIsFilter(useAsFilterCheckBox.isSelected());
                }
            }
        });
        
        //set up visibility
        setMandatory(true);
        mandatoryLabel.setVisible(false);
        addButton.setEnabled(false);
        removeButton.setEnabled(false);
        applyButton.setEnabled(false);
        
        //fill tableCombo
        tableCombo.addItem(tableComboDefault);
        for(ModifiableTableSchema m : MedSavantDatabase.getInstance().getModifiableTables()){
            tableCombo.addItem(m);
        }
        
        //fill typeCombo
        for(ColumnType ct : ColumnType.values()){
            typeCombo.addItem(ct);
        }
        
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        columnList = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        columnNameField = new javax.swing.JTextField();
        shortNameField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        lengthField = new javax.swing.JTextField();
        mandatoryLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        removeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        useAsFilterCheckBox = new javax.swing.JCheckBox();
        tableCombo = new javax.swing.JComboBox();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setText("Choose column:");

        jScrollPane1.setViewportView(columnList);

        addButton.setText("Add Column");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("DB Column Name:");

        jLabel3.setText("Short Name:");

        jLabel4.setText("Description:");

        jLabel5.setText("Type:");

        jLabel6.setText("Length");

        columnNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnNameFieldActionPerformed(evt);
            }
        });

        mandatoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mandatoryLabel.setText("This is a mandatory column and cannot be modified. ");

        removeButton.setText("Remove Column");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Use as Filter:");

        useAsFilterCheckBox.setText(" ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(removeButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(addButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(useAsFilterCheckBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(lengthField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .add(descriptionField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .add(shortNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .add(columnNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .add(typeCombo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(mandatoryLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(columnNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(shortNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(descriptionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(typeCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(lengthField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(useAsFilterCheckBox))
                        .add(18, 18, 18)
                        .add(mandatoryLabel))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 291, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addButton)
                    .add(removeButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableComboActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 792, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tableCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .add(okButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(applyButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 496, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tableCombo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(applyButton)
                    .add(cancelButton)
                    .add(okButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addNewColumn();
}//GEN-LAST:event_addButtonActionPerformed

    private void columnNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnNameFieldActionPerformed
        
}//GEN-LAST:event_columnNameFieldActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        removeSelectedColumn();
}//GEN-LAST:event_removeButtonActionPerformed

    private void tableComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableComboActionPerformed
        Object o = tableCombo.getSelectedItem();
        if(!o.equals(tableComboDefault)){
            populateColumnList((ModifiableTableSchema)o, null);
            this.currentSchema = (ModifiableTableSchema)o;
        }
}//GEN-LAST:event_tableComboActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        apply();
}//GEN-LAST:event_applyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancel();
        close();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        apply();
        close();
}//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JList columnList;
    private javax.swing.JTextField columnNameField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lengthField;
    private javax.swing.JLabel mandatoryLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField shortNameField;
    private javax.swing.JComboBox tableCombo;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JCheckBox useAsFilterCheckBox;
    // End of variables declaration//GEN-END:variables

//listeners
        
    
    private void populateColumnList(ModifiableTableSchema m, ModifiableColumn select){
        currentColumn = null;
        List<ModifiableColumn> columns = m.getModColumns();
        DefaultListModel model = new DefaultListModel();        
        for(ModifiableColumn col : columns){
            if(!col.isRemoved())
                model.addElement(col);
        }
        columnList.setModel(model);
        if(select != null){
            int index = model.indexOf(select);
            if(index >= 0){
                columnList.setSelectedIndex(index);
            }
        }
        applyButton.setEnabled(true);
        addButton.setEnabled(true);
        removeButton.setEnabled(true);
    }
    
    private void setMandatory(boolean mandatory){
        mandatoryLabel.setVisible(mandatory);
        columnNameField.setEnabled(!mandatory);
        shortNameField.setEnabled(!mandatory);
        descriptionField.setEnabled(!mandatory);
        typeCombo.setEnabled(!mandatory);
        lengthField.setEnabled(!mandatory);
        useAsFilterCheckBox.setEnabled(!mandatory);
    }
    
    private void populateDetails(ModifiableColumn c){
        currentColumn = null;
        columnNameField.setText(c.getColumnName());
        shortNameField.setText(c.getShortName());
        descriptionField.setText(c.getDescription());
        typeCombo.setSelectedItem(c.getType());
        lengthField.setText(String.valueOf(c.getLength()));
        useAsFilterCheckBox.setSelected(c.isFilter());
        setMandatory(c.isMandatory());
        if(!c.isNew()){
            typeCombo.setEnabled(false);
            lengthField.setEnabled(false);
        } 
        currentColumn = c;
    }
    
    private void clearDetails(){
        columnNameField.setText("");
        shortNameField.setText("");
        descriptionField.setText("");
        lengthField.setText("");
        setMandatory(true);
        mandatoryLabel.setVisible(false);
    }

    private void addNewColumn(){
        String tempName = currentSchema.getUntitledString();
        ModifiableColumn c = new ModifiableColumn(tempName, tempName, "", ColumnType.VARCHAR, 250, false, false, true);
        currentSchema.addModColumn(c);
        populateColumnList(currentSchema, c);
        populateDetails(c);
    }
    
    private void removeSelectedColumn(){
        if(currentColumn != null && !currentColumn.isMandatory()){
            currentColumn.setRemoved(true);
            populateColumnList(currentSchema, null);
            clearDetails();
            currentColumn = null;
        }
    }
    
    private void apply(){
        
        //TODO: error checking on updates!!!
        
        for(ModifiableTableSchema m : MedSavantDatabase.getInstance().getModifiableTables()){
            try {
                m.applyChanges();
            } catch (SQLException ex) {
                Logger.getLogger(ManageDB.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NonFatalDatabaseException ex) {
                Logger.getLogger(ManageDB.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void cancel(){
        for(ModifiableTableSchema m : MedSavantDatabase.getInstance().getModifiableTables()){
            m.removeChanges();
        }
    }
    
    private void close(){
        MedSavantDatabase.getInstance().refreshModifiableTables();
        ViewController.getInstance().refreshView();
        this.setVisible(false);
    }


}
